- name: Debug Playbook
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Print environment variables
      command: env
      register: env_output

    - name: Show environment variables
      debug:
        var: env_output.stdout_lines

    - name: Print OS version
      debug:
        msg: "OS Version: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Example conditional task
      debug:
        msg: "This task runs only if ansible_distribution is Ubuntu"
      when: ansible_distribution == 'Ubuntu'

