- name: Thu thập thông tin hệ thống và log từ các máy chủ
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Hiển thị thông tin phiên bản hệ điều hành
      debug:
        msg: "Hệ điều hành: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Đọc tệp syslog
      command: cat /var/log/syslog
      register: syslog_content
      become: yes

    - name: Hiển thị nội dung của syslog theo từng dòng
      debug:
        msg: |
          {% if syslog_content.stdout %}
          Nội dung của tệp syslog:
          {% for line in syslog_content.stdout.split('\n') %}
            - {{ line }}
          {% endfor %}
          {% else %}
          Tệp syslog không có nội dung.
          {% endif %}

    - name: Thu thập thông tin về các gói phần mềm
      ansible.builtin.package_facts:
        manager: auto

    - name: Hiển thị tên các gói phần mềm đã cài đặt theo bảng
      debug:
        msg: |
          {% if ansible_facts.packages %}
          Danh sách gói phần mềm đã cài đặt:
          | Tên Gói      | Phiên Bản    |
          |--------------|--------------|
          {% for pkg_name, pkg_info in ansible_facts.packages.items() %}
          | {{ pkg_name }} | {{ pkg_info[0].version if pkg_info else 'N/A' }} |
          {% endfor %}
          {% else %}
          Không có thông tin về gói phần mềm.
          {% endif %}

