---
# Play cho Ubuntu
- name: Playbook for Linux
  hosts: linux
  become: yes
  tasks:
    - name: Ping the Ubuntu hosts
      ping:

# Play cho Windows
- name: Playbook for Windows
  hosts: windows
  tasks:
    - name: Ping the Windows hosts
      win_ping:


