---
- hosts: all
  tasks:
    - name: Ping Test on Linux
      when: ansible_os_family == "Linux"
      ping:

    - name: Ping Test on Windows
      when: ansible_os_family == "Windows"
      win_ping:
