---
# Play cho Ubuntu
- name: Playbook for Linux
  hosts: linux
  become: yes
  tasks:
    - name: Ping the Ubuntu hosts
      ping:

    - name: Install necessary packages on Ubuntu
      apt:
        name:
          - curl
          - vim
        state: present
      when: ansible_os_family == "Debian"

    - name: Check syslog on Ubuntu
      shell: "grep -i error /var/log/syslog"
      register: syslog_errors
      ignore_errors: yes

    - name: Truncate syslog errors if too long
      set_fact:
        truncated_syslog_errors: "{{ syslog_errors.stdout[:4000] }}"
      when: syslog_errors.stdout != ""

    - name: Send Telegram message for Ubuntu syslog errors
      uri:
        url: "https://api.telegram.org/bot7607504619:AAEM0ViUgqtDb7BWf01SQGA_V_D0yDHQt44/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "chat_id": "1959952679",
            "text": "Syslog errors detected on {{ inventory_hostname }}: {{ truncated_syslog_errors }}"
          }
        status_code: 200
      when: syslog_errors.stdout != ""

# Play cho Windows
- name: Playbook for Windows
  hosts: windows
  tasks:
    - name: Ping the Windows hosts
      win_ping:

    - name: Install necessary applications on Windows
      win_feature:
        name: Web-Server
        state: present
      when: ansible_os_family == "Windows"

    - name: Check Event Log for Errors on Windows
      win_shell: "Get-EventLog -LogName System -EntryType Error"
      register: event_log_errors
      ignore_errors: yes

    - name: Truncate Event Log errors if too long
      set_fact:
        truncated_event_log_errors: "{{ event_log_errors.stdout[:4000] }}"
      when: event_log_errors.stdout != ""

    - name: Send Telegram message for Windows Event Log errors
      uri:
        url: "https://api.telegram.org/bot7607504619:AAEM0ViUgqtDb7BWf01SQGA_V_D0yDHQt44/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "chat_id": "1959952679",
            "text": "Event Log errors detected on {{ inventory_hostname }}: {{ truncated_event_log_errors }}"
          }
        status_code: 200
      when: event_log_errors.stdout != ""
