---
# Play cho Ubuntu
- name: Playbook for Linux
  hosts: linux
  become: yes
  tasks:
    - name: Ping the Ubuntu hosts
      ping:

    - name: Install necessary packages on Ubuntu
      apt:
        name:
          - curl
          - vim
        state: present
      when: ansible_os_family == "Debian"

    - name: Check syslog on Ubuntu
      shell: "grep -i error /var/log/syslog"
      register: syslog_errors
      ignore_errors: yes

    - name: Write syslog errors to a file
      copy:
        content: "{{ syslog_errors.stdout }}"
        dest: "/tmp/syslog_errors_{{ inventory_hostname }}.txt"
      when: syslog_errors.stdout != ""

    - name: Send Telegram message for Ubuntu syslog errors (with file link)
      uri:
        url: "https://api.telegram.org/botYOUR_BOT_TOKEN/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "chat_id": "YOUR_CHAT_ID",
            "text": "Syslog errors detected on {{ inventory_hostname }}. See the errors in the attached file."
          }
        status_code: 200
      when: syslog_errors.stdout != ""

# Play cho Windows
- name: Playbook for Windows
  hosts: windows
  tasks:
    - name: Ping the Windows hosts
      win_ping:

    - name: Install necessary applications on Windows
      win_feature:
        name: Web-Server
        state: present
      when: ansible_os_family == "Windows"

    - name: Check Event Log for Errors on Windows
      win_shell: "Get-EventLog -LogName System -EntryType Error"
      register: event_log_errors
      ignore_errors: yes

    - name: Write Event Log errors to a file
      win_copy:
        content: "{{ event_log_errors.stdout }}"
        dest: "C:\\temp\\event_log_errors_{{ inventory_hostname }}.txt"
      when: event_log_errors.stdout != ""

    - name: Send Telegram message for Windows Event Log errors (with file link)
      uri:
        url: "https://api.telegram.org/botYOUR_BOT_TOKEN/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "chat_id": "YOUR_CHAT_ID",
            "text": "Event Log errors detected on {{ inventory_hostname }}. See the errors in the attached file."
          }
        status_code: 200
      when: event_log_errors.stdout != ""
