---
- name: Cài đặt các phần mềm cần thiết trên Ubuntu
  hosts: linux
  become: yes
  roles:
    - set_up

- name: Cài đặt các phần mềm cần thiết trên Windows
  hosts: windows
  roles:
    - set_up_win
