---
- name: Cài đặt các phần mềm cần thiết trên Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Cập nhật danh sách gói
      apt:
        update_cache: yes

    - name: Nâng cấp tất cả các gói
      apt:
        upgrade: dist

    - name: Cài đặt Git
      apt:
        name: git
        state: present

    - name: Cài đặt curl
      apt:
        name: curl
        state: present

    - name: Cài đặt wget
      apt:
        name: wget
        state: present

    - name: Cài đặt vim
      apt:
        name: vim
        state: present

    - name: Cài đặt htop
      apt:
        name: htop
        state: present

    - name: Cài đặt tmux
      apt:
        name: tmux
        state: present

    - name: Cài đặt build-essential và các công cụ phát triển
      apt:
        name:
          - build-essential
          - gcc
          - g++
          - make
          - cmake
        state: present

    - name: Cài đặt các thư viện phát triển
      apt:
        name:
          - libssl-dev
          - libffi-dev
          - python3-dev
          - zlib1g-dev
        state: present

    - name: Cài đặt Python và pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Cài đặt Java Development Kit
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Cài đặt Node.js và npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Cài đặt MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Cài đặt PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Cài đặt SQLite
      apt:
        name: sqlite3
        state: present

    - name: Cài đặt Docker
      apt:
        name: docker.io
        state: present

    - name: Cài đặt Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Cài đặt VirtualBox
      apt:
        name: virtualbox
        state: present

    - name: Cài đặt net-tools
      apt:
        name: net-tools
        state: present

    - name: Cài đặt nmap
      apt:
        name: nmap
        state: present

    - name: Cài đặt iftop
      apt:
        name: iftop
        state: present

    - name: Cài đặt Firefox
      apt:
        name: firefox
        state: present

    - name: Cài đặt Chromium Browser
      apt:
        name: chromium-browser
        state: present

