---
# Play cho Windows
- name: Playbook for Windows
  hosts: windows
  tasks:
    - name: Ping the Windows hosts
      win_ping:

    - name: Install IIS on Windows
      win_shell: |
        Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServer -All

    - name: Check Event Log for Errors on Windows
      win_shell: "Get-EventLog -LogName System -EntryType Error | Where-Object { $_.TimeGenerated -gt (Get-Date).AddMinutes(-30) }"
      register: event_log_errors
      ignore_errors: yes

    - name: Debug Event Log errors output
      debug:
        var: event_log_errors.stdout

    - name: Truncate Event Log errors if too long
      set_fact:
        truncated_event_log_errors: "{{ event_log_errors.stdout[:4000] }}"
      when: event_log_errors.stdout != ""

    - name: Send Telegram message for Windows Event Log errors
      win_uri:
        url: "https://api.telegram.org/bot7607504619:AAEM0ViUgqtDb7BWf01SQGA_V_D0yDHQt44/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'chat_id': '1959952679', 'text': 'Event Log errors detected on ' + inventory_hostname + ': ' + truncated_event_log_errors} | to_json }}"
        status_code: 200
      when: event_log_errors.stdout != ""

    - name: Send Telegram message if no Event Log errors
      win_uri:
        url: "https://api.telegram.org/bot7607504619:AAEM0ViUgqtDb7BWf01SQGA_V_D0yDHQt44/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'chat_id': '1959952679', 'text': 'No Event Log errors detected on ' + inventory_hostname + ' in the last 30 minutes.'} | to_json }}"
        status_code: 200
      when: event_log_errors.stdout == ""

