---
- name: Create and serve a timetable HTML file with editable table
  hosts: controller
  vars:
    ansible_user: candi
  become: yes
  tasks:
    - name: Ensure Python is installed
      apt:
        name: python3
        state: present

    - name: Create timetable directory
      file:
        path: /opt/timetable
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create the timetable HTML file with editable table
      copy:
        dest: /opt/timetable/timetable.html
        content: |
          <!DOCTYPE html>
          <html lang="vi">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Thời Gian Biểu</title>
              <style>
                  table {
                      width: 100%;
                      border-collapse: collapse;
                  }
                  table, th, td {
                      border: 1px solid black;
                  }
                  th, td {
                      padding: 10px;
                      text-align: center;
                  }
                  th {
                      background-color: #f2f2f2;
                  }
                  .editable {
                      cursor: pointer;
                      background-color: #f9f9f9;
                  }
                  .editable:focus {
                      outline: 2px solid #007bff;
                  }
              </style>
              <script>
                  function makeEditable(cell) {
                      cell.contentEditable = true;
                      cell.focus();
                  }

                  function saveData() {
                      const table = document.querySelector('table');
                      const rows = table.querySelectorAll('tr');
                      const data = {};

                      rows.forEach((row, rowIndex) => {
                          const cells = row.querySelectorAll('td');
                          cells.forEach((cell, cellIndex) => {
                              if (cell.contentEditable === "true") {
                                  const hour = rowIndex;
                                  const day = cellIndex;
                                  const value = cell.innerText;
                                  data[`entry_${hour}_${day}`] = value;
                              }
                          });
                      });

                      fetch('/submit_event', {
                          method: 'POST',
                          headers: {
                              'Content-Type': 'application/json'
                          },
                          body: JSON.stringify(data)
                      }).then(response => response.text())
                        .then(result => alert(result));
                  }
              </script>
          </head>
          <body>
              <h2>Thời Gian Biểu</h2>
              <table>
                  <tr>
                      <th>Giờ/Ngày</th>
                      <th>Thứ Hai</th>
                      <th>Thứ Ba</th>
                      <th>Thứ Tư</th>
                      <th>Thứ Năm</th>
                      <th>Thứ Sáu</th>
                      <th>Thứ Bảy</th>
                      <th>Chủ Nhật</th>
                  </tr>
                  {% for hour in range(0, 24) %}
                  <tr>
                      <td>{{ '%02d:00' % hour }}</td>
                      {% for day in range(0, 7) %}
                      <td class="editable" onclick="makeEditable(this)"></td>
                      {% endfor %}
                  </tr>
                  {% endfor %}
              </table>
              <button onclick="saveData()">Save Changes</button>
          </body>
          </html>

    - name: Create a systemd service to serve the timetable
      copy:
        dest: /etc/systemd/system/timetable.service
        content: |
          [Unit]
          Description=Serve timetable HTML file
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 -m http.server 8000 --directory /opt/timetable
          WorkingDirectory=/opt/timetable
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply changes
      command: systemctl daemon-reload

    - name: Enable and start the timetable service
      systemd:
        name: timetable
        state: started
        enabled: yes
