---
- name: Update Flask Web Server Content
  hosts: controller
  become: yes
  tasks:

    - name: Update the Flask app file with new content
      copy:
        dest: /opt/flask_app/app.py
        content: |
          from flask import Flask, request, render_template_string
          app = Flask(__name__)

          @app.route('/', methods=['GET', 'POST'])
          def home():
              if request.method == 'POST':
                  return '''
                  <!doctype html>
                  <html lang="en">
                    <head>
                      <meta charset="utf-8">
                      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                      <title>Kết quả</title>
                      <style>
                        .centered {
                          text-align: center;
                          font-size: 48px;
                          margin-top: 20%;
                        }
                      </style>
                    </head>
                    <body>
                      <div class="centered">Bạn rất đẹp trai</div>
                    </body>
                  </html>
                  '''
              return '''
                  <!doctype html>
                  <html lang="en">
                    <head>
                      <meta charset="utf-8">
                      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                      <title>Câu hỏi</title>
                    </head>
                    <body>
                      <h1>Bạn sẽ chọn một người đàn ông:</h1>
                      <form method="post">
                        <button type="submit" name="choice" value="dep_trai">Đẹp trai</button>
                        <button type="submit" name="choice" value="giau_co">Giàu có</button>
                      </form>
                    </body>
                  </html>
              '''

          if __name__ == "__main__":
              app.run(host='0.0.0.0', port=5000)
      notify: Restart Flask app service

  handlers:
    - name: Restart Flask app service
      systemd:
        name: flask_app
        state: restarted
        enabled: yes
