---
- name: Update Quiz Web App
  hosts: controller
  become: yes
  tasks:
    - name: Update the Flask app file with new content
      copy:
        dest: /opt/flask_app/app.py
        content: |
          from flask import Flask, render_template, request, redirect, url_for
          from flask_sqlalchemy import SQLAlchemy

          app = Flask(__name__)
          app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///quiz.db'
          db = SQLAlchemy(app)

          class Quiz(db.Model):
              id = db.Column(db.Integer, primary_key=True)
              question = db.Column(db.String(200), nullable=False)
              answer = db.Column(db.String(200), nullable=False)

          @app.route('/')
          def home():
              quizzes = Quiz.query.all()
              return render_template('home.html', quizzes=quizzes)

          @app.route('/add', methods=['GET', 'POST'])
          def add():
              if request.method == 'POST':
                  question = request.form['question']
                  answer = request.form['answer']
                  new_quiz = Quiz(question=question, answer=answer)
                  try:
                      db.session.add(new_quiz)
                      db.session.commit()
                      return redirect('/')
                  except:
                      return 'There was an issue adding your quiz'
              else:
                  return render_template('add.html')

          @app.route('/quiz/<int:id>')
          def quiz(id):
              quiz = Quiz.query.get_or_404(id)
              return render_template('quiz.html', quiz=quiz)

          if __name__ == "__main__":
              db.create_all()
              app.run(host='0.0.0.0', port=5000)

    - name: Ensure the Flask app service file is updated
      copy:
        dest: /etc/systemd/system/flask_app.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve flask_app
          After=network.target

          [Service]
          User=root
          Group=www-data
          WorkingDirectory=/opt/flask_app
          Environment="PATH=/opt/flask_app/venv/bin"
          ExecStart=/opt/flask_app/venv/bin/gunicorn --workers 3 --bind unix:flask_app.sock -m 007 app:app

          [Install]
          WantedBy=multi-user.target
      notify: Restart Flask app service

    - name: Copy the Flask app templates
      copy:
        dest: /opt/flask_app/templates/home.html
        content: |
          {% raw %}
          <!doctype html>
          <html>
          <head>
              <title>Quiz App</title>
          </head>
          <body>
              <h1>Welcome to the Quiz App</h1>
              <a href="/add">Add a New Quiz</a>
              <ul>
              {% for quiz in quizzes %}
                  <li><a href="/quiz/{{ quiz.id }}">{{ quiz.question }}</a></li>
              {% endfor %}
              </ul>
          </body>
          </html>
          {% endraw %}
        mode: 0644
        owner: root
        group: www-data

    - name: Copy the add quiz template
      copy:
        dest: /opt/flask_app/templates/add.html
        content: |
          {% raw %}
          <!doctype html>
          <html>
          <head>
              <title>Add a New Quiz</title>
          </head>
          <body>
              <h1>Add a New Quiz</h1>
              <form method="POST">
                  <label for="question">Question:</label><br>
                  <input type="text" id="question" name="question"><br>
                  <label for="answer">Answer:</label><br>
                  <input type="text" id="answer" name="answer"><br><br>
                  <input type="submit" value="Submit">
              </form>
          </body>
          </html>
          {% endraw %}
        mode: 0644
        owner: root
        group: www-data

    - name: Copy the quiz detail template
      copy:
        dest: /opt/flask_app/templates/quiz.html
        content: |
          {% raw %}
          <!doctype html>
          <html>
          <head>
              <title>Quiz Detail</title>
          </head>
          <body>
              <h1>{{ quiz.question }}</h1>
              <p>{{ quiz.answer }}</p>
          </body>
          </html>
          {% endraw %}
        mode: 0644
        owner: root
        group: www-data

  handlers:
    - name: Restart Flask app service
      systemd:
        name: flask_app
        state: restarted
        enabled: yes
