---
- name: Install all critical and security updates
  win_updates:
    category_names:
    - CriticalUpdates
    - SecurityUpdates
    state: installed
  register: update_result

- name: Reboot host if required
  win_reboot:
  when: update_result.reboot_required

- name: Xóa tệp vlc.install.nupkg không hợp lệ
  win_file:
    path: C:\ProgramData\chocolatey\lib\vlc.install\vlc.install.nupkg
    state: absent

- name: Đảm bảo Chocolatey được cài đặt
  win_chocolatey:
    name: all
    state: latest
