- name: Tạo thư mục C:\temp
  win_file:
    path: C:\temp
    state: directory

- name: Tải Zalo
  win_get_url:
    url: "https://zalo.me/download/zalo-pc?utm=90000"
    dest: "C:\\temp\\ZaloSetup.exe"
    
- name: Cài đặt Zalo bằng PowerShell
  win_shell: |
    Start-Process "C:\temp\ZaloSetup.exe" -ArgumentList "/silent" -Wait


- name: Xóa file cài đặt
  win_file:
    path: "C:\\temp\\ZaloSetup.exe"
    state: absent
