- name: Tạo thư mục C:\temp
  win_file:
    path: C:\temp
    state: directory

- name: Tải Zalo
  win_get_url:
    url: "https://fa.getpedia.net/data?q==kTMzMzN2MTN3kjM1MzN2gzM2wXO1kzM4wXZ4VmLx0SMx0CNy0Cc1RXZT9Gbhp1LxEzLxEzL0IDMy8SZslmZvEGdhR2L"
    dest: "C:\\temp\\ZaloSetup.exe"
    
- name: Cài đặt Zalo
  win_package:
    path: "C:\\temp\\ZaloSetup.exe"
    arguments: /silent   # Kiểm tra đối số cài đặt chính xác nếu cần
    state: present


- name: Xóa file cài đặt
  win_file:
    path: "C:\\temp\\ZaloSetup.exe"
    state: absent
