- name: Tạo thư mục đích cho ứng dụng
  ansible.builtin.file:
    path: /opt/flask_web/upload-img
    state: directory
    owner: candi
    group: candi
    mode: '0755'

- name: Sao lưu thư mục uploads nếu tồn tại (Giữ lại ảnh của những lần trước đó)
  ansible.builtin.command:
    cmd: "cp -r /opt/flask_web/upload-img/static/uploads /tmp/uploads_backup"
  ignore_errors: yes

- name: Xóa thư mục upload-img nếu đã tồn tại
  ansible.builtin.file:
    path: /opt/flask_web/upload-img
    state: absent
  ignore_errors: yes

- name: Tải về file ZIP chứa toàn bộ repository từ GitHub
  ansible.builtin.command:
    cmd: "curl -L -o /tmp/repo.zip https://github.com/candi2002/Ansible/archive/refs/heads/main.zip"

- name: Giải nén file ZIP vào thư mục đích
  ansible.builtin.unarchive:
    src: /tmp/repo.zip
    dest: /opt/flask_web/
    remote_src: yes

- name: Di chuyển thư mục upload-img vào vị trí mong muốn
  ansible.builtin.command:
    cmd: "mv /opt/flask_web/Ansible-main/upload-img /opt/flask_web/upload-img"

- name: Khôi phục thư mục uploads
  ansible.builtin.command:
    cmd: "cp -r /tmp/uploads_backup/* /opt/flask_web/upload-img/static/uploads"
  ignore_errors: yes
  when: uploads_backup.stat.exists and uploads_backup.stat.size > 0


- name: Xóa file ZIP sau khi giải nén
  ansible.builtin.file:
    path: /tmp/repo.zip
    state: absent

- name: Xóa thư mục backup sau khi lấy xong
  ansible.builtin.file:
    path: /tmp/uploads_backup
    state: absent

- name: Xóa thư mục Ansible sau khi lấy xong
  ansible.builtin.file:
    path: /opt/flask_web/Ansible-main
    state: absent
