- name: Create target directory for the application
  ansible.builtin.file:
    path: /opt/flask_web/upload-img
    state: directory
    owner: candi
    group: candi
    mode: '0755'

- name: Backup the uploads directory if it exists (Preserve previous images)
  ansible.builtin.command:
    cmd: "cp -r /opt/flask_web/upload-img/static/uploads /opt/flask_web/uploads_backup"
  ignore_errors: yes

- name: Remove the upload-img directory if it exists
  ansible.builtin.file:
    path: /opt/flask_web/upload-img
    state: absent
  ignore_errors: yes

- name: Download the ZIP file containing the entire repository from GitHub
  ansible.builtin.command:
    cmd: "curl -L -o /tmp/repo.zip https://github.com/candi2002/Ansible/archive/refs/heads/main.zip"

- name: Unarchive the ZIP file into the target directory
  ansible.builtin.unarchive:
    src: /tmp/repo.zip
    dest: /opt/flask_web/
    remote_src: yes

- name: Move the upload-img directory to the desired location
  ansible.builtin.command:
    cmd: "mv /opt/flask_web/Ansible-main/upload-img /opt/flask_web/upload-img"

- name: Restore the uploads directory
  ansible.builtin.shell:
    cmd: "cp -r /opt/flask_web/uploads_backup/* /opt/flask_web/upload-img/static/uploads"
  ignore_errors: yes
  become: yes

- name: Remove the ZIP file after extraction
  ansible.builtin.file:
    path: /tmp/repo.zip
    state: absent

- name: Remove the backup directory after use
  ansible.builtin.file:
    path: /opt/flask_web/uploads_backup
    state: absent
  become: yes  

- name: Remove the Ansible directory after use
  ansible.builtin.file:
    path: /opt/flask_web/Ansible-main
    state: absent
