---
# download_and_unzip/tasks/main.yml

- name: Tải về file ZIP từ GitHub
  ansible.builtin.command:
    cmd: "curl -L -o /tmp/web.zip https://github.com/candi2002/Ansible/archive/3020f429699e400e1528aa4acd6d14bc3064c552.zip"
  args:
    warn: false

- name: Giải nén file ZIP vào thư mục đích
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /opt/flask_web/
    remote_src: yes

- name: Đổi tên thư mục sau khi giải nén
  ansible.builtin.command:
    cmd: "mv /opt/flask_web/Ansible-3020f429699e400e1528aa4acd6d14bc3064c552 /opt/flask_web/my_upload_img"
  args:
    removes: /opt/flask_web/my_upload_img  # Chỉ chạy nếu thư mục chưa tồn tại

- name: Kiểm tra nếu thư mục đã được đổi tên thành công
  ansible.builtin.stat:
    path: /opt/flask_web/my_upload_img
  register: rename_check

- name: Xác nhận việc đổi tên thành công
  ansible.builtin.debug:
    msg: "Thư mục đã được đổi tên thành công!"
  when: rename_check.stat.exists
