---
- name: Ensure virtual environment is created
  command: python3 -m venv /opt/flask_web/upload-img/venv
  args:
    creates: /opt/flask_web/upload-img/venv

- name: Install Flask and dependencies in virtual environment
  command: /opt/flask_web/upload-img/venv/bin/pip install Flask flask_sqlalchemy gunicorn
  args:
    chdir: /opt/flask_web/upload-img

- name: Create systemd service for Flask app
  become: yes  # Thêm quyền root cho task này
  copy:
    dest: /etc/systemd/system/upload_flask_app.service
    content: |
      [Unit]
      Description=Gunicorn instance to serve Flask app
      After=network.target

      [Service]
      User=candi
      Group=www-data
      WorkingDirectory=/opt/flask_web/upload-img
      Environment="PATH=/opt/flask_web/upload-img/venv/bin"
      ExecStart=/opt/flask_web/upload-img/venv/bin/python /opt/flask_web/upload-img/youframe.py

      [Install]
      WantedBy=multi-user.target
  notify: Restart Flask app service  # Gọi handler để restart Flask app sau khi tạo service

- name: Reload systemd to apply new service
  become: yes  # Thêm quyền root cho task này
  command: systemctl daemon-reload

- name: Enable and start Flask app service
  become: yes  # Thêm quyền root cho task này
  systemd:
    name: upload_flask_app
    state: started
    enabled: yes
  notify: Restart Flask app service  # Gọi handler sau khi dịch vụ được enable và start
