---
- name: Ensure the '/opt/flask_web/upload-img' directory and its contents have correct permissions
  become: yes
  file:
    path: /opt/flask_web/upload-img
    owner: candi
    group: www-data
    mode: '0775'
    state: directory
    recurse: yes
    
- name: Ensure virtual environment is created
  become: yes  # Thêm quyền root cho task này
  command: python3 -m venv /opt/flask_web/upload-img/venv
  args:
    creates: /opt/flask_web/upload-img/venv

- name: Install Flask and dependencies in virtual environment
  become: yes  # Thêm quyền root cho task này
  command: /opt/flask_web/upload-img/venv/bin/pip install Flask flask_sqlalchemy gunicorn
  args:
    chdir: /opt/flask_web/upload-img

- name: Create systemd service for Flask app
  become: yes  # Thêm quyền root cho task này
  copy:
    dest: /etc/systemd/system/upload_flask_app.service
    content: |
      [Unit]
      Description=Gunicorn instance to serve Flask app
      After=network.target

      [Service]
      User=candi
      Group=www-data
      WorkingDirectory=/opt/flask_web/upload-img
      Environment="PATH=/opt/flask_web/upload-img/venv/bin"
      ExecStart=/opt/flask_web/upload-img/venv/bin/python /opt/flask_web/upload-img/youframe.py

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply new service
  become: yes  # Thêm quyền root cho task này
  command: systemctl daemon-reload
  notify:
    - Restart Flask app service  # Gọi handler sau khi reload systemd

- name: Enable and start Flask app service
  become: yes  # Thêm quyền root cho task này
  systemd:
    name: upload_flask_app
    state: started
    enabled: yes
