---
- name: Check who am I
  shell: whoami
  register: w

- name: Display user information
  debug:
    msg: "{{ w.stdout }}"

- name: Create systemd service for Flask app
  copy:
    dest: /etc/systemd/system/flask_web.service
    content: |
      [Unit]
      Description=Gunicorn instance to serve Flask web app
      After=network.target

      [Service]
      User=candi
      Group=www-data
      WorkingDirectory=/opt/flask_web/upload-img
      Environment="PATH=/opt/flask_web/upload-img/venv/bin"
      ExecStart=/opt/flask_web/upload-img/venv/bin/python /opt/flask_web/upload-img/youframe.py

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  command: systemctl daemon-reload

- name: Enable and start Flask web app service
  systemd:
    name: flask_web
    state: started
    enabled: yes

- name: Open port 5000 on the firewall (if needed)
  ufw:
    rule: allow
    port: 5000
    proto: tcp
    comment: "Allow Flask web server traffic on port 5000"

- name: Check Flask web app service status
  shell: systemctl status flask_web
  register: service_status
  ignore_errors: yes

- name: Debug service status
  debug:
    msg: "{{ service_status.stdout }}"
