---
- name: Ensure Flask app dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-venv

- name: Ensure the Flask app virtual environment is activated
  command: /opt/flask_web/upload-img/venv/bin/python /opt/flask_web/upload-img/youframe.py
  args:
    chdir: /opt/flask_web/upload-img
