- name: Ensure virtual environment is created
  command: python3 -m venv /opt/flask_web/upload-img/venv
  args:
    creates: /opt/flask_web/upload-img/venv

- name: Install Flask and dependencies in virtual environment
  command: /opt/flask_web/upload-img/venv/bin/pip install Flask flask_sqlalchemy gunicorn
  args:
    chdir: /opt/flask_web/upload-img

- name: Ensure the 'static/uploads' directory has correct permissions
  become: yes  # Thêm quyền root cho task này
  file:
    path: /opt/flask_web/upload-img/static/uploads
    owner: candi
    group: www-data
    mode: '0775'
    state: directory

- name: Create systemd service for Flask app
  become: yes  # Thêm quyền root cho task này
  copy:
    dest: /etc/systemd/system/upload_flask_app.service
    content: |
      [Unit]
      Description=Gunicorn instance to serve Flask app
      After=network.target

      [Service]
      User=candi
      Group=www-data
      WorkingDirectory=/opt/flask_web/upload-img
      Environment="PATH=/opt/flask_web/upload-img/venv/bin"
      ExecStart=/opt/flask_web/upload-img/venv/bin/python /opt/flask_web/upload-img/youframe.py

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply new service
  become: yes  # Thêm quyền root cho task này
  command: systemctl daemon-reload

- name: Enable and start Flask app service
  become: yes  # Thêm quyền root cho task này
  systemd:
    name: upload_flask_app
    state: started
    enabled: yes

# Handlers placed here
handlers:
  - name: Restart Flask app service
    systemd:
      name: upload_flask_app
      state: restarted
      enabled: yes
